twitter.consumerKey="9iCZgYe9EsRgZgnAy74Z9Eg9D"
twitter.consumerSecret="uvAsV1whpCYX6UJqfqEIaLj3tulVg7PQEV4Qas1iUUBoLrnJE9"
twitter.accessToken="251645597-MZOp2z4zb2Tj2gABsVzKeBjN6zDgrU2V7s7Zgp32"
twitter.accessTokenSecret="MNqY4bPO3dxosm0ccv8uXRIQlVdMUAd9FAwXpcsZAEw4n"

topicName = "twitter"
servers = "localhost:9092"